version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "127.0.0.1:80:4000"
    volumes:
      - ./:/app
    command: yarn dev
    depends_on:
      - db
  db:
    image: percona:8
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
